name: PersistentDataLib
version: '${project.version}'
main: io.github.grgadam.persistentdatalib.PersistentDataLib
api-version: 1.17
authors: [ GrGadam ]
description: A library of useful codes for other plugins.
